### ISSUE TITLE
Line Profile plugin with QGIS 3.24 

### ISSUE THREAD

**Issue by Cmattheou** [wiscsims/line_profile#4]
Using Line Profile Plugin with QGIS 3.24 resulting with the following error:

2022-03-05T12:40:46     WARNING    Python error : Couldn't load plugin 'line_profile' due to an error when calling its classFactory() method See message log (Python Error) for more details.

Working fine though with QGIS 3.16
Regards
Charalambos

**Comment by saburo** [comment]
Thanks for the report. 
Unfortunately, I could not reproduce the error in my environment. It would be helpful to know the more details of the error.


My environment:
macOS Monterey (12.2.1)
QGIS 3.24
Line Profile 3.1.1

**Comment by Cmattheou** [comment]
Hi. This is the whole massage
I am using QGIS 3.24 on WIN 10. I hope it hepl's

Couldn't load plugin 'line_profile' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~2.0/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/bambo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\line_profile\__init__.py", line 35, in classFactory
    from .line_profile import LineProfile
  File "C:\PROGRA~1/QGIS32~2.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/bambo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\line_profile\line_profile.py", line 58, in 
    from .tools.plottingTool import PlottingTool
  File "C:\PROGRA~1/QGIS32~2.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/bambo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\line_profile\tools\plottingTool.py", line 6, in 
    from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
  File "C:\PROGRA~1/QGIS32~2.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.24.0-Tisler Tisler, 6b44a42058 

Python Path:
C:\Users/bambo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenTopography-DEM-Downloader
C:\Users/bambo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\noise_prediction
C:/PROGRA~1/QGIS32~2.0/apps/qgis/./python
C:/Users/bambo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/bambo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~2.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.24.0\bin\python39.zip
C:\PROGRA~1\QGIS32~2.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~2.0\apps\Python39\lib
C:\Program Files\QGIS 3.24.0\bin
C:\Users\bambo\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~2.0\apps\Python39
C:\PROGRA~1\QGIS32~2.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~2.0\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~2.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~2.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~2.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/bambo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.

**Comment by saburo** [comment]
Thanks for the details.
It seems that the problem was caused by loading a deprecated module (for some reason this did not happen in my environment). 

> ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg'

I have uploaded a modified version, which you can try by installing the [zip file](https://github.com/wiscsims/line_profile/releases/download/v3.1.2/line_profile.zip). I have also uploaded it to the [QGIS Python Plugins Repository](https://plugins.qgis.org/plugins/), so it should be approved soon. Then you can update it as usual in the QGIS Plug-in Manager.

I hope this fixes the problem.

**Comment by Cmattheou** [comment]
THANKS, WORKING FINE ON QGIS 3.24
